/**
 * A prototype script to process standard analysis tree.
 *
 * anatree_core.h (generated by the TTree::MakeClass() method) and
 * anatree.h (a wrapper for the former) are needed
 **/


#include "anatree.h"


void standard_ana_example(const char* fname, const char* outpref)
{
    //***** Output Histograms *****
    auto h = new TH1F("hE", "Initial Energy of G4 Particles;Energy [GeV]", 500, 0, 5000);

    //***** Input tree *****
    auto tree = new TChain("analysistree/anatree");
    int status = tree->Add(fname);
    if (! status) {
	cout<<"Can't find tree "<< tree->GetName() << " in file "<<fname<<endl;
	return;
    } else {
	cout<<"Will process tree "<< tree->GetName() << " in file "<<fname<<endl;
    }

    anatree* evt = new anatree(tree);

    // allow only selected branches!
    //
    // This improves the speed of the tree processing. Any branch to
    // be used needs to be added here, otherwise we don't get any data
    // from it.
    std::vector<TString> allowed = {
    	"geant_list_size",
	"Eng",
    };
    tree->SetBranchStatus("*", 0);
    AnaTree::AllowBranches(tree, allowed);


    //***** Process *****
    cout<<"Starting a loop over the tree"<<endl;
    int size = tree->GetEntries();
    cout<<"Will loop over "<<size<<" entries."<<endl;

    for (int ientry = 0; ientry < size; ++ientry) {
	tree->GetEntry(ientry);

	// fill the histogram with all particles' energies
	int nparticles = evt->geant_list_size;
	for (int ipart = 0; ipart < nparticles; ++ipart) {
	    h->Fill(evt->Eng[ipart]);
	}
    }

    cout<<"Done."<<endl;


    // Draw the results
    h->Draw();

    // set log scale on y axis
    gPad->SetLogy();

    // Save the canvas into a pdf file
    gPad->SaveAs(Form("%senergies.pdf", outpref));

    //***** Output file *****
    auto outf = TFile::Open(Form("%sanahists.root", outpref), "UPDATE");

    //***** Save hists *****
    h->Write(0, TObject::kOverwrite);

    outf->Close();
    cout<<"Saved and closed output file"<<endl;
}
