/**
 * A prototype script to process standard analysis tree.
 *
 * You can run like:
 *
 * $ root -l -b -q 'scripts/standard_ana_example.C("path_to_your_file.root","test")'
 *
 * to process 1 file, or
 *
 * $ rootbq 'scripts/standard_ana_example.C("", "test", 23, 20)'
 *
 * to process 20 files from our production batch 20002300.
 *
 * Takes 2 mandatory and 2 optional arguments:
 *   - fname (string) = name of the input file (if empty, "", will process production files)
 *   - outpref (string) = prefix for the output file name
 *   - batchNo (integer, optional, default 21) = which production batch to use to load data
 *   - Nruns (integer, ptional, default 10) = how many runs from the batch to process
 *
 * anatree_core.h (generated by the TTree::MakeClass() method) and
 * anatree.h (a wrapper for the former) are needed
 **/


#include "anatree.h"

void attachFiles(TChain* tree, const char* fname, int batchNo, int Nruns) {
     if (!strcmp(fname, "")) { // no input given
	cout<<"Will add production files from batch "
	    <<batchNo<<" to the chain (unchecked)."<<endl;
	TString batch = Form("2000%02d", batchNo);
	TString topdir = "/data/kumar/dune/cosmic/largeproduction/data/";
	topdir += batch + "00/";
	for (int j = 0; j<Nruns; j++) {
	    TString fname = topdir +
		Form(batch + "%02d/MUSUN_dunefd_" + batch + "%02d_gen_g4_detsim_reco_ana.root",
		     j, j);
	    int status = tree->Add(fname, 500);
	}
    } else { // input given
	cout<<"Adding "<<fname<<" to the chain."<<endl;
	int status = tree->Add(fname, -1);
	if (!status) { // try to look in the base dir
	    tree->SetName("anatree");
	    status = tree->Add(fname, -1);
	}
	cout<<"Status: "<<status<<endl;
    }
}


void standard_ana_example(const char* fname, const char* outpref, int batchNo = 21, int Nruns = 10)
{
    //***** Output Histograms *****

    // Energies of protons directly produced by the primary muon inside the TPC AV
    auto hEproton = new TH1F("hEproton", "Initial Energy of protons;Energy [GeV]", 100, 0, 10);
    // Positions of where protons were produced by the primary muon inside the TPC AV
    auto hPosProton = new TH3F("hPosProton", "Initial positions of protons;X [cm];Y [cm];Z [cm]", 160, -800, 800, 140, -700, 700, 300, 0., 6e3);
    // see https://root.cern.ch/doc/master/classTH1.html for description of TH1F and TH3F


    //***** Input tree *****
    auto tree = new TChain("analysistree/anatree");
    attachFiles(tree, fname, batchNo, Nruns);

    // Create an object that will hold data from the analysis tree
    // entries.  The the tree is instructed to set it's branch
    // adresses to respective variables in this object. (See
    // https://root.cern.ch/root/htmldoc/guides/users-guide/Trees.html#trees,
    // namely sections 14.1, 14.2 - 14.6, and also
    // https://root.cern.ch/doc/master/classTTree.html#creatingattree
    // and
    // https://root.cern.ch/doc/master/classTTree.html#addcolumnoffundamentaltypes)
    anatree* evt = new anatree(tree);



    // allow only selected branches!
    //
    // This improves the speed of the tree processing. Any branch to
    // be used needs to be added here, otherwise we don't get any data
    // from it.
    //
    // TTree::SetBranchStatus(branch_name, status) tells the tree
    // which braches it should load data from. 'status == 0' = don't
    // load; 'status == 1' = load.
    //
    // Function AnaTree::AllowBranches() simply loops over all string
    // in the input list 'allowed' and calls
    // TTree::SetBranchStatus(allowed_item, 1), which instructs the
    // tree to always load data from that branch.
    //
    std::vector<TString> allowed = {
    	"geant_list_size",
	"Eng",
	"inTPCActive",
	"Mother",
	"pdg",
	"StartPointx",
	"StartPointy",
	"StartPointz",
    };
    tree->SetBranchStatus("*", 0);
    AnaTree::AllowBranches(tree, allowed);


    //***** Process *****
    cout<<"Starting a loop over the tree"<<endl;
    int size = tree->GetEntries();
    cout<<"Will loop over "<<size<<" entries."<<endl;

    for (int ientry = 0; ientry < size; ++ientry) {
	tree->GetEntry(ientry);

	// fill the histogram with all particles' energies
	int nparticles = evt->geant_list_size;
	for (int ipart = 0; ipart < nparticles; ++ipart) {
	    if (evt->pdg[ipart] == 2212 && evt->Mother[ipart] == 1 && evt->inTPCActive[ipart] == 1) {
		// this particle is proton, its mother is the primary particle, and it has reached/been produced in TPC AV
		hEproton->Fill(evt->Eng[ipart]);
		hPosProton->Fill(evt->StartPointx[ipart],evt->StartPointy[ipart],evt->StartPointz[ipart]);
	    }
	}
    }

    cout<<"Done."<<endl;


    // Draw the results
    // hEproton->Draw();

    // set log scale on y axis
    //gPad->SetLogy();

    // Save the canvas into a pdf file
    //gPad->SaveAs(Form("%sproton_energies.pdf", outpref));

    //***** Output file *****
    auto outf = TFile::Open(Form("%sanahists.root", outpref), "UPDATE");

    //***** Save hists *****
    hEproton->Write(0, TObject::kOverwrite);
    hPosProton->Write(0, TObject::kOverwrite);

    outf->Close();
    cout<<"Saved and closed output file"<<endl;
}
